name: Deploy to GitHub pages

on:
  # trigger deployment on every push to main branch
  push:
    branches:
      - main
  # trigger deployment manually
  workflow_dispatch:
  # trigger deployment on new release publication
  release:
    types:
      - published

# allow the action to deploy to gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Install and Build 🔧
        run: |
          cd documentation
          npm ci
          npm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: documentation/docs/.vuepress/dist # The folder the action should deploy.